# Generated by Django 4.2 on 2025-01-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adtext', models.CharField(default='这是广告位置, 10秒后消失', max_length=100)),
                ('showTime', models.IntegerField(default=10)),
                ('imgStart', models.CharField(default='', max_length=100)),
                ('imgEnd', models.CharField(default='', max_length=100)),
                ('epgUrl', models.CharField(default='', max_length=100)),
                ('ua', models.CharField(default='SYTV/1.6', max_length=100)),
            ],
        ),
    ]
