# Generated by Django 4.2 on 2025-01-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicsetting',
            name='startCount',
            field=models.IntegerField(default=0),
        ),
    ]
