# Generated by Django 4.2 on 2025-01-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceAdmin', '0005_remove_device_cansee'),
        ('softAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='devices',
            field=models.ManyToManyField(related_name='canSee', to='deviceAdmin.device'),
        ),
    ]
