# Generated by Django 4.2 on 2025-01-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softAdmin', '0002_category_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
