# Generated by Django 4.2 on 2025-01-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softAdmin', '0003_channel_hidden_alter_category_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='channel',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
