# Generated by Django 4.2 on 2025-01-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macAddress', models.CharField(max_length=17)),
                ('androidId', models.CharField(max_length=64)),
                ('deviceName', models.CharField(max_length=64)),
                ('ipAddress', models.GenericIPAddressField()),
                ('ipArea', models.CharField(max_length=64)),
                ('lastOnlineTime', models.DateTimeField(auto_now_add=True)),
                ('isAuthorized', models.BooleanField(default=False)),
            ],
        ),
    ]
