# Generated by Django 4.2 on 2025-01-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='startCount',
            field=models.IntegerField(default=0),
        ),
    ]
