# Generated by Django 4.2 on 2025-01-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceAdmin', '0002_device_startcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='lastOnlineTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
