# Generated by Django 4.2 on 2025-01-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceAdmin', '0003_alter_device_lastonlinetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='canSee',
            field=models.CharField(default='', max_length=64),
        ),
    ]
