# Generated by Django 4.2 on 2025-01-25 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deviceAdmin', '0004_device_cansee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='canSee',
        ),
    ]
