# Generated by Django 4.2 on 2025-01-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='avatar',
            field=models.CharField(default='', max_length=255),
        ),
    ]
